# Generated by Django 2.2.16 on 2022-06-07 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220606_1925'),
        ('users', '0003_auto_20220606_1844'),
    ]

    operations = [
    ]
