# Generated by Django 2.2.16 on 2022-06-09 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220609_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Выберите от 1 до 10'), django.core.validators.MaxValueValidator(10, 'Выберите от 1 до 10')]),
        ),
    ]
