# Generated by Django 2.2.16 on 2022-06-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220601_1745'),
        ('reviews', '0003_auto_20220601_2252'),
    ]

    operations = [
    ]
